version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: poesias
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql